### ISSUE TITLE
The API doesn't require a password to share a secret

### ISSUE THREAD

**Issue by armando82** [chelnak/OneTimeSecret#7]
This is not a bug. The script works as intended but it's not 100% true to the API which allows to create secrets without the need of pre-shared passwords.

Could you please make the password parameter optional?

**Comment by chelnak** [comment]
Good point. I’ll look in to making the change.

**Comment by chelnak** [comment]
This is now resolved as of 2.1.0!

Thanks for your interest.

**Comment by armando82** [comment]
Thank you, but it's not resolved. The [ValidateNotNullOrEmpty()] check is preventing this argument from being effectively optional.

**Comment by chelnak** [comment]
Can you provide me with an example of the way you are invoking the function and the error you get when invoking it?

That validation should only happen if you pass the parameter with nothing assigned to it.

Thanks

**Comment by armando82** [comment]
I'm not passing the passphrase parameter. And then the cmdlet requests a value for that parameter even if it's not mandatory:
New-OTSSharedSecret -Secret $Secret -Recipient $Email
I clearly uninstalled and reinstalled the module.

**Comment by chelnak** [comment]
Please can you post the output of:

```PowerShell
Get-Module *OneTimeSecret* -ListAvailable
```

**Comment by chelnak** [comment]
While checking for your issue, i found another small bug which i fixed. It might be worth you updating to the latest version (2.1.1)

```PowerShell
Update-Module OneTimeSecret
```

**Comment by armando82** [comment]
Ok, now I'm getting something different. It's complaining about me not using the Set-OTSConnectionInformation first. Should be fine now. Thank you!

**Comment by armando82** [comment]
One last request, that might merit another thread. Any chances of allowing to set the base URL to a private instance of OTS?

**Comment by chelnak** [comment]
I don’t see why not. Please open a new issue for a new feature.

Glad your issue is sorted. I’ll close this thread shortly.

**Comment by chelnak** [comment]
Closing as #8 exists
